export const MIT_LICENSE = `MIT License

Copyright (c) 2024 Student Deployment System

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`;

export function generateReadmeTemplate(task, brief, repoUrl, round = 1) {
  const pagesUrl = repoUrl.replace('github.com', `${process.env.GITHUB_USERNAME}.github.io`).replace(/^https:\/\/([^\/]+)\/([^\/]+)$/, 'https://$1.github.io/$2');
  
  return `# ${task}

## Project Overview
This application was automatically generated as part of a student evaluation system.

### Brief
${brief}

### Round
${round === 1 ? 'Initial Build' : 'Revision'}

## Live Demo
🌐 **Live Application**: [${pagesUrl}](${pagesUrl})

## Repository
📁 **Source Code**: [${repoUrl}](${repoUrl})

## Features
- Single-page web application
- Responsive design
- Self-contained HTML, CSS, and JavaScript
- Deployed via GitHub Pages

## Usage
1. Open the [live demo](${pagesUrl}) in your browser
2. The application will automatically load and function based on the requirements
3. Any URL parameters specified in the brief will be processed automatically

## Technical Details
- **Framework**: Pure HTML5, CSS3, JavaScript (ES6+)
- **Deployment**: GitHub Pages
- **License**: MIT

## Evaluation
This project was generated and deployed automatically as part of round ${round} of the student evaluation process.

---

*Automatically generated by Student Deployment System*`;
}